version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "novachronicles-agent-stack"
s3_bucket = "novachronicles-sam-artifacts"
s3_prefix = "novachronicles"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "APP_ENVIRONMENT=\"production\""
